public class HelloWorld {
  public static void main(String[] args){
    System.out.print("Hello World");
  }
}


public class HideAndSeek {
  public static void main(String[] args) {

    System.out.println("Let's play hide and seek.");
    System.out.println("I'll hide, you seek!");
//println ^ prints on separate lines

    System.out.print("Let's play hide and seek.");
    System.out.print("I'll hide, you seek!");
//print^ prints on same lines

  }
}
